/*
 * Author: Ahmed A.
 * Submission Date: 11/26/2018
 * This GUI program calculates and displays a rugby match analysis according to user input
 */

/**
 *
 * @author Ahmed A.
 */
public class rugbyStatsGui extends javax.swing.JFrame {

    public rugbyStatsGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPnl = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        team1Lbl = new javax.swing.JLabel();
        team2Lbl = new javax.swing.JLabel();
        tm1Pnt3Fld = new javax.swing.JTextField();
        tm1Pnt5Fld = new javax.swing.JTextField();
        tm1Pnt2Fld = new javax.swing.JTextField();
        tm1KickAttemptFld = new javax.swing.JTextField();
        tm1TckCmpltFld = new javax.swing.JTextField();
        tm1TckMissFld = new javax.swing.JTextField();
        tm1LnOutWinFld = new javax.swing.JTextField();
        tm1LnOutLossFld = new javax.swing.JTextField();
        tm1ScrumWinFld = new javax.swing.JTextField();
        tm1ScrumLossFld = new javax.swing.JTextField();
        pnt3Lbl = new javax.swing.JLabel();
        pnt5Lbl = new javax.swing.JLabel();
        pnt2Lbl = new javax.swing.JLabel();
        kickAttemptLbl = new javax.swing.JLabel();
        tckCmpltLbl = new javax.swing.JLabel();
        tckMissLbl = new javax.swing.JLabel();
        lnoutWinLbl = new javax.swing.JLabel();
        lnoutLossLbl = new javax.swing.JLabel();
        scrumWinLbl = new javax.swing.JLabel();
        scrumLossLbl = new javax.swing.JLabel();
        tm2Pnt3Fld = new javax.swing.JTextField();
        tm2Pnt5Fld = new javax.swing.JTextField();
        tm2Pnt2Fld = new javax.swing.JTextField();
        tm2KickAttemptFld = new javax.swing.JTextField();
        tm2TckCmpltFld = new javax.swing.JTextField();
        tm2TckMissFld = new javax.swing.JTextField();
        tm2LnOutWinFld = new javax.swing.JTextField();
        tm2LnOutLossFld = new javax.swing.JTextField();
        tm2ScrumWinFld = new javax.swing.JTextField();
        tm2ScrumLossFld = new javax.swing.JTextField();
        processBtn = new javax.swing.JButton();
        tm1TotalPntLbl = new javax.swing.JLabel();
        tm1TcklPrcntLbl = new javax.swing.JLabel();
        tm1LnOutPrcntLbl = new javax.swing.JLabel();
        tm1ScrumPrcntLbl = new javax.swing.JLabel();
        tm1KickPrcntLbl = new javax.swing.JLabel();
        totalPntLbl = new javax.swing.JLabel();
        tcklPrcntLbl = new javax.swing.JLabel();
        lnoutPrcntLbl = new javax.swing.JLabel();
        scrumPrcntLbl = new javax.swing.JLabel();
        kickPrcntLbl = new javax.swing.JLabel();
        tm2TotalPntLbl = new javax.swing.JLabel();
        tm2TcklPrcntLbl = new javax.swing.JLabel();
        tm2LnOutPrcntLbl = new javax.swing.JLabel();
        tm2ScrumPrcntLbl = new javax.swing.JLabel();
        tm2KickPrcntLbl = new javax.swing.JLabel();
        titleLbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Match Statistics");
        titleLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        team1Lbl.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        team1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        team1Lbl.setText("Team 1");
        team1Lbl.setMaximumSize(new java.awt.Dimension(200, 50));

        team2Lbl.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        team2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        team2Lbl.setText("Team 2");
        team2Lbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tm1Pnt3Fld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1Pnt3Fld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1Pnt3Fld.setText("0");

        tm1Pnt5Fld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1Pnt5Fld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1Pnt5Fld.setText("0");

        tm1Pnt2Fld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1Pnt2Fld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1Pnt2Fld.setText("0");

        tm1KickAttemptFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1KickAttemptFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1KickAttemptFld.setText("0");

        tm1TckCmpltFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1TckCmpltFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1TckCmpltFld.setText("0");

        tm1TckMissFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1TckMissFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1TckMissFld.setText("0");

        tm1LnOutWinFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1LnOutWinFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1LnOutWinFld.setText("0");

        tm1LnOutLossFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1LnOutLossFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1LnOutLossFld.setText("0");

        tm1ScrumWinFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1ScrumWinFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1ScrumWinFld.setText("0");

        tm1ScrumLossFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1ScrumLossFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1ScrumLossFld.setText("0");

        pnt3Lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnt3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnt3Lbl.setText("Penalties/Drop Goals");
        pnt3Lbl.setMaximumSize(new java.awt.Dimension(200, 50));

        pnt5Lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnt5Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnt5Lbl.setText("Tries");
        pnt5Lbl.setMaximumSize(new java.awt.Dimension(200, 50));

        pnt2Lbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnt2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnt2Lbl.setText("Conversions");
        pnt2Lbl.setMaximumSize(new java.awt.Dimension(200, 50));

        kickAttemptLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kickAttemptLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kickAttemptLbl.setText("Kicks Attempted");
        kickAttemptLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tckCmpltLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tckCmpltLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tckCmpltLbl.setText("Tackles Completed");
        tckCmpltLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tckMissLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tckMissLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tckMissLbl.setText("Tackles Missed");
        tckMissLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        lnoutWinLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lnoutWinLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnoutWinLbl.setText("Lineouts Won");
        lnoutWinLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        lnoutLossLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lnoutLossLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnoutLossLbl.setText("Lineouts Lost");
        lnoutLossLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        scrumWinLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scrumWinLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scrumWinLbl.setText("Scrums Won");
        scrumWinLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        scrumLossLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scrumLossLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scrumLossLbl.setText("Scrums Lost");
        scrumLossLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tm2Pnt3Fld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2Pnt3Fld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm2Pnt3Fld.setText("0");

        tm2Pnt5Fld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2Pnt5Fld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm2Pnt5Fld.setText("0");

        tm2Pnt2Fld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2Pnt2Fld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm2Pnt2Fld.setText("0");

        tm2KickAttemptFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2KickAttemptFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm2KickAttemptFld.setText("0");

        tm2TckCmpltFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2TckCmpltFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm2TckCmpltFld.setText("0");

        tm2TckMissFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2TckMissFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm2TckMissFld.setText("0");

        tm2LnOutWinFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2LnOutWinFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm2LnOutWinFld.setText("0");

        tm2LnOutLossFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2LnOutLossFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm2LnOutLossFld.setText("0");

        tm2ScrumWinFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2ScrumWinFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm2ScrumWinFld.setText("0");

        tm2ScrumLossFld.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2ScrumLossFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm2ScrumLossFld.setText("0");

        processBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        processBtn.setText("Process Information");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        tm1TotalPntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1TotalPntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tm1TotalPntLbl.setText("0");
        tm1TotalPntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tm1TcklPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1TcklPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tm1TcklPrcntLbl.setText("0");
        tm1TcklPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tm1LnOutPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1LnOutPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tm1LnOutPrcntLbl.setText("0");
        tm1LnOutPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tm1ScrumPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1ScrumPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tm1ScrumPrcntLbl.setText("0");
        tm1ScrumPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tm1KickPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm1KickPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tm1KickPrcntLbl.setText("0");
        tm1KickPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        totalPntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalPntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPntLbl.setText("Overall Points");
        totalPntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tcklPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tcklPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tcklPrcntLbl.setText("Tackle Success %");
        tcklPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        lnoutPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lnoutPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lnoutPrcntLbl.setText("Lineouts Success %");
        lnoutPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        scrumPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scrumPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scrumPrcntLbl.setText("Scrums Success %");
        scrumPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        kickPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kickPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kickPrcntLbl.setText("Kicking Success %");
        kickPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tm2TotalPntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2TotalPntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tm2TotalPntLbl.setText("0");
        tm2TotalPntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tm2TcklPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2TcklPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tm2TcklPrcntLbl.setText("0");
        tm2TcklPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tm2LnOutPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2LnOutPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tm2LnOutPrcntLbl.setText("0");
        tm2LnOutPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tm2ScrumPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2ScrumPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tm2ScrumPrcntLbl.setText("0");
        tm2ScrumPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        tm2KickPrcntLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tm2KickPrcntLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tm2KickPrcntLbl.setText("0");
        tm2KickPrcntLbl.setMaximumSize(new java.awt.Dimension(200, 50));

        titleLbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl1.setText("Input your data into the text fields, ensuring all text fields have a number");
        titleLbl1.setMaximumSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout bgPnlLayout = new javax.swing.GroupLayout(bgPnl);
        bgPnl.setLayout(bgPnlLayout);
        bgPnlLayout.setHorizontalGroup(
            bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPnlLayout.createSequentialGroup()
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPnlLayout.createSequentialGroup()
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgPnlLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgPnlLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPnlLayout.createSequentialGroup()
                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(team1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tm1Pnt3Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tm1Pnt5Fld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(tm1Pnt2Fld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tm1KickAttemptFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tm1TckCmpltFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(tm1TckMissFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tm1LnOutWinFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tm1LnOutLossFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(tm1ScrumWinFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(tm1ScrumLossFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgPnlLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(team2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgPnlLayout.createSequentialGroup()
                                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(bgPnlLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pnt5Lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lnoutWinLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tckMissLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tckCmpltLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(pnt3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(scrumLossLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(scrumWinLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lnoutLossLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(pnt2Lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPnlLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(kickAttemptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tm2Pnt3Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tm2Pnt5Fld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tm2Pnt2Fld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tm2KickAttemptFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tm2TckCmpltFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tm2TckMissFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tm2LnOutWinFld, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tm2LnOutLossFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tm2ScrumWinFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(tm2ScrumLossFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(bgPnlLayout.createSequentialGroup()
                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tm1KickPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tm1ScrumPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tm1LnOutPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tm1TcklPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tm1TotalPntLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kickPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrumPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lnoutPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tcklPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalPntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tm2TotalPntLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tm2TcklPrcntLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tm2LnOutPrcntLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tm2ScrumPrcntLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tm2KickPrcntLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(titleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        bgPnlLayout.setVerticalGroup(
            bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(team1Lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(team2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgPnlLayout.createSequentialGroup()
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pnt3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tm2Pnt3Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tm2Pnt5Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnt5Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tm2Pnt2Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnt2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tm2KickAttemptFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kickAttemptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tm2TckCmpltFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tckCmpltLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tm2TckMissFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tckMissLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tm2LnOutWinFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnoutWinLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tm2LnOutLossFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnoutLossLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tm2ScrumWinFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrumWinLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tm2ScrumLossFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrumLossLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgPnlLayout.createSequentialGroup()
                        .addComponent(tm1Pnt3Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tm1Pnt5Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tm1Pnt2Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tm1KickAttemptFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tm1TckCmpltFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tm1TckMissFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tm1LnOutWinFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tm1LnOutLossFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tm1ScrumWinFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tm1ScrumLossFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(processBtn)
                .addGap(11, 11, 11)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm2TotalPntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm1TotalPntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcklPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm1TcklPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm2TcklPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnoutPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm1LnOutPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm2LnOutPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scrumPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm2ScrumPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm1ScrumPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kickPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm1KickPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm2KickPrcntLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed

        //Variable declaration and initialization to extract numbers from text fields
        int pdGoal1 = Integer.parseInt(tm1Pnt3Fld.getText()), try1 = Integer.parseInt(tm1Pnt5Fld.getText()), cnvrsn1 = Integer.parseInt(tm1Pnt2Fld.getText()), kickAttempt1 = Integer.parseInt(tm1KickAttemptFld.getText()), tckCmplt1 = Integer.parseInt(tm1TckCmpltFld.getText()), tckMiss1 = Integer.parseInt(tm1TckMissFld.getText()), lnOutWin1 = Integer.parseInt(tm1LnOutWinFld.getText()), lnOutLoss1 = Integer.parseInt(tm1LnOutLossFld.getText()), scrumWin1 = Integer.parseInt(tm1ScrumWinFld.getText()), scrumLoss1 = Integer.parseInt(tm1ScrumLossFld.getText());
        int pdGoal2 = Integer.parseInt(tm2Pnt3Fld.getText()), try2 = Integer.parseInt(tm2Pnt5Fld.getText()), cnvrsn2 = Integer.parseInt(tm2Pnt2Fld.getText()), kickAttempt2 = Integer.parseInt(tm2KickAttemptFld.getText()), tckCmplt2 = Integer.parseInt(tm2TckCmpltFld.getText()), tckMiss2 = Integer.parseInt(tm2TckMissFld.getText()), lnOutWin2 = Integer.parseInt(tm2LnOutWinFld.getText()), lnOutLoss2 = Integer.parseInt(tm2LnOutLossFld.getText()), scrumWin2 = Integer.parseInt(tm2ScrumWinFld.getText()), scrumLoss2 = Integer.parseInt(tm2ScrumLossFld.getText());

        /* Set the output labels of the overall points of team 1/2 according
        to the tries, conversions, and penalty/drop goals inputted by the user */
        tm1TotalPntLbl.setText(Integer.toString(overallPoints(pdGoal1, try1, cnvrsn1)));
        tm2TotalPntLbl.setText(Integer.toString(overallPoints(pdGoal2, try2, cnvrsn2)));

        /* Set the output labels of the tackle success percentage of team 1/2
        according to the completed and missed tackles inputted by the user */
        tm1TcklPrcntLbl.setText(Integer.toString(tackles(tckCmplt1, tckMiss1)));
        tm2TcklPrcntLbl.setText(Integer.toString(tackles(tckCmplt2, tckMiss2)));

        /* Set the output labels of the lineouts success percentage of team 1/2
        according to the lineout wins and losses inputted by the user */
        tm1LnOutPrcntLbl.setText(Integer.toString(lineouts(lnOutWin1, lnOutLoss1)));
        tm2LnOutPrcntLbl.setText(Integer.toString(lineouts(lnOutWin2, lnOutLoss2)));

        /* Set the output labels of the scrums success percentage of team 1/2
        according to the scrum wins and losses inputted by the user */
        tm1ScrumPrcntLbl.setText(Integer.toString(scrums(scrumWin1, scrumLoss1)));
        tm2ScrumPrcntLbl.setText(Integer.toString(scrums(scrumWin2, scrumLoss2)));

        /* Set the output labels of the kicking success percentage of team 1/2
        according to the completed and missed kicks inputted by the user */
        tm1KickPrcntLbl.setText(Integer.toString(kicks(pdGoal1, cnvrsn1, kickAttempt1)));
        tm2KickPrcntLbl.setText(Integer.toString(kicks(pdGoal2, cnvrsn2, kickAttempt2)));
    }//GEN-LAST:event_processBtnActionPerformed

    /**
     * This method finds the sum of all the points scored by the teams by multiplying
     * the number of   tries, penalty/drop goals, or conversions, by a constant that 
     * stores the number of points gained by each type of scoring type.
     * @param pdGoal
     * @param tries
     * @param cnvrsn
     * @return points
     */
    
    public static int overallPoints(int pdGoal, int tries, int cnvrsn) {

        //Constant declaration and initialization area
        final int CNVRSN = 2, TRY = 5, PDGOAL = 3;

        //Declaring points variable, and calculating it as sum of penalty/drop goals, tries, and conversions
        int points = (PDGOAL * pdGoal) + (TRY * tries) + (CNVRSN * cnvrsn);

        return points;
    }

    /**
     * This method calculates the tackling success rate
     * @param tckCmplt
     * @param tckMiss
     * @return tacklesPrcnt
     */
    public static int tackles(int tckCmplt, int tckMiss) {

        //Declare tackles percent variable
        int tacklesPrcnt = 1;

        /* "If statement" to only calculate the tackle completion percentage when there are more than 0
        overall tackles (sum of completed and missed tackles), therefore avoiding division by 0 */
        if ((tckCmplt + tckMiss) > 0) {

            /* Initializing tackles percent variable, and calculating it as the quotient
            between the completed tackles and the total tackles (sum of completed and
            missed tackles), then multiplying it by 100 to express it as a percentage */
            tacklesPrcnt = (tckCmplt * 100) / (tckCmplt + tckMiss);
        } 
        
        /* "Else if statement" displays a tackling completion percent of 0 when no tackles are completed */
        else if (tckCmplt == 0) {

            tacklesPrcnt = 0;
        } else {

            /* Initializing tackle completion percent variable as 100, because there are no missed
            tackles, therefore the tackle completion rate is 100% */
            tacklesPrcnt = 100;
        }

        return tacklesPrcnt;
    }
    
    /**
     * This method calculates the lineouts win rate
     * @param lnOutWin
     * @param lnOutLoss
     * @return lineoutsPrcnt
     */
    public static int lineouts(int lnOutWin, int lnOutLoss) {

        int lineoutsPrcnt = 1;

        /* "If statement" to only calculate the lineout win percentage when there are more than 0
        overall lineouts (sum of won and lost lineouts), therefore avoiding division by 0 */
        if ((lnOutWin + lnOutLoss) > 0) {

            /* Initializing lineouts percent variable, and calculating it as the quotient
            between the lineouts won and the total lineouts (sum of lineouts won and
            lineouts lost), then multiplying it by 100 to express it as a percentage */
            lineoutsPrcnt = (lnOutWin * 100) / (lnOutWin + lnOutLoss);
        } 
        
        /* "Else if statement" displays a lineout win percent of 0 when no lineouts are won */ 
        else if (lnOutWin == 0) {

            lineoutsPrcnt = 0;
        } else {

            /* Initializing lineouts win percent variable as 100, because there are no lost
            lineouts, therefore the lineouts win rate is 100% */
            lineoutsPrcnt = 100;
        }

        return lineoutsPrcnt;
    }

    /**
     * This method calculates the scrum win rate
     * @param scrumWin
     * @param scrumLoss
     * @return scrumPrcnt
     */
    public static int scrums(int scrumWin, int scrumLoss) {

        int scrumPrcnt = 1;

        /* "If statement" to only calculate the scrum win percentage when there are more than 0
        overall scrums (sum of won and lost scrums), therefore avoiding division by 0 */
        if ((scrumWin + scrumLoss) > 0) {

            /* Initializing scrums percent variable, and calculating it as the quotient
            between the scrums won and the total scrums (sum of scrums won and
            scrums lost), then multiplying it by 100 to express it as a percentage */
            scrumPrcnt = (scrumWin * 100) / (scrumWin + scrumLoss);
        } 
        
        /* "Else if statement" displays a scrum win percent of 0 when no scrums are won */ 
        else if (scrumWin == 0) {

            scrumPrcnt = 0;
        } else {

            /* Initializing scrum win percent variable as 100, because there are no lost
            scrums, therefore the scrum win rate is 100% */
            scrumPrcnt = 100;
        }

        return scrumPrcnt;
    }

    /**
     * This method calculates the kicking accuracy rate
     * @param pdGoal
     * @param cnvrsn
     * @param kickAttempt
     * @return kickPrcnt
     */
    public static int kicks(int pdGoal, int cnvrsn, int kickAttempt) {

        int kickPrcnt = 1;

        /* "If statement" to only calculate the kicking accuracy percentage when
        there are more than 0 kick attempts, therefore avoiding division by 0 */
        if (kickAttempt > 0) {

            /* Initializing kicking percent variable, and calculating it as the quotient
            between the total kicks (sum of penalty/drop goals and conversions) and the 
            total kick attempts, then multiplying it by 100 to express it as a percentage */
            kickPrcnt = ((pdGoal + cnvrsn) * 100) / kickAttempt;
        } 
        
        /* "Else if statement" displays a kicking percent of 0 when no kicks are scored */ 
        else if ((pdGoal + cnvrsn) == 0) {

            kickPrcnt = 0;
        } else {

            /* Initializing kicking percent variable as 100, because there are no missed
            kicks, therefore the kicking accuracy rate is 100% */
            kickPrcnt = 100;
        }

        return kickPrcnt;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rugbyStatsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rugbyStatsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rugbyStatsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rugbyStatsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rugbyStatsGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPnl;
    private javax.swing.JLabel kickAttemptLbl;
    private javax.swing.JLabel kickPrcntLbl;
    private javax.swing.JLabel lnoutLossLbl;
    private javax.swing.JLabel lnoutPrcntLbl;
    private javax.swing.JLabel lnoutWinLbl;
    private javax.swing.JLabel pnt2Lbl;
    private javax.swing.JLabel pnt3Lbl;
    private javax.swing.JLabel pnt5Lbl;
    private javax.swing.JButton processBtn;
    private javax.swing.JLabel scrumLossLbl;
    private javax.swing.JLabel scrumPrcntLbl;
    private javax.swing.JLabel scrumWinLbl;
    private javax.swing.JLabel tckCmpltLbl;
    private javax.swing.JLabel tckMissLbl;
    private javax.swing.JLabel tcklPrcntLbl;
    private javax.swing.JLabel team1Lbl;
    private javax.swing.JLabel team2Lbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel titleLbl1;
    private javax.swing.JTextField tm1KickAttemptFld;
    private javax.swing.JLabel tm1KickPrcntLbl;
    private javax.swing.JTextField tm1LnOutLossFld;
    private javax.swing.JLabel tm1LnOutPrcntLbl;
    private javax.swing.JTextField tm1LnOutWinFld;
    private javax.swing.JTextField tm1Pnt2Fld;
    private javax.swing.JTextField tm1Pnt3Fld;
    private javax.swing.JTextField tm1Pnt5Fld;
    private javax.swing.JTextField tm1ScrumLossFld;
    private javax.swing.JLabel tm1ScrumPrcntLbl;
    private javax.swing.JTextField tm1ScrumWinFld;
    private javax.swing.JTextField tm1TckCmpltFld;
    private javax.swing.JTextField tm1TckMissFld;
    private javax.swing.JLabel tm1TcklPrcntLbl;
    private javax.swing.JLabel tm1TotalPntLbl;
    private javax.swing.JTextField tm2KickAttemptFld;
    private javax.swing.JLabel tm2KickPrcntLbl;
    private javax.swing.JTextField tm2LnOutLossFld;
    private javax.swing.JLabel tm2LnOutPrcntLbl;
    private javax.swing.JTextField tm2LnOutWinFld;
    private javax.swing.JTextField tm2Pnt2Fld;
    private javax.swing.JTextField tm2Pnt3Fld;
    private javax.swing.JTextField tm2Pnt5Fld;
    private javax.swing.JTextField tm2ScrumLossFld;
    private javax.swing.JLabel tm2ScrumPrcntLbl;
    private javax.swing.JTextField tm2ScrumWinFld;
    private javax.swing.JTextField tm2TckCmpltFld;
    private javax.swing.JTextField tm2TckMissFld;
    private javax.swing.JLabel tm2TcklPrcntLbl;
    private javax.swing.JLabel tm2TotalPntLbl;
    private javax.swing.JLabel totalPntLbl;
    // End of variables declaration//GEN-END:variables
}
